name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.0.1

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_remote_config: ^2.0.8
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  drift: ^1.6.0
  drift_inspector: ^1.0.1
  path_provider: ^2.0.10
  package_info_plus: ^1.4.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.7
  unsplash_client: ^2.1.0+3
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  lints: ^1.0.1
  mockito: ^5.2.0
  drift_dev: ^1.6.0
  network_image_mock: ^2.1.0
  transparent_image: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
