desc "Submit a new internal build to Play Store"
lane :deploy do
  upload_to_play_store(
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_apk: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
  )
end

desc "Promote previous internal version to production"
lane :promote do
  upload_to_play_store(
      track: "internal",
      track_promote_to: "production"
  )
end
